/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Table_Selector */

#ifndef _Included_application_Table_Selector
#define _Included_application_Table_Selector
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
